### ISSUE TITLE
bbnj reference

### ISSUE THREAD

**Issue by mvisalli** [BenioffOceanInitiative/s4wr#2]
https://github.com/mvisalli/shipr/blob/ecacff311c8eb5040f26f57953b682aeb1d521dc/data-raw/sbais.R#L7

Hey @bbest should this be shipr::read_ais_txt ?

**Comment by bbest** [comment]
Yes indeed, good find Morgan!

Do you want to try fixing that? Then git commit with message saying "fixed #2" and push. This will automatically close this issue ;)

**Comment by bbest** [comment]
Well done :)
